# Generated by Django 4.0.4 on 2022-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_photo', models.ImageField(null=True, upload_to='', verbose_name='первое фото')),
                ('second_photo', models.ImageField(null=True, upload_to='', verbose_name='второе фото')),
                ('name', models.CharField(max_length=50, verbose_name='название одежды')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='стоимость')),
                ('link_kufar', models.URLField(verbose_name='ссылка на куфар')),
            ],
        ),
    ]
