# Generated by Django 4.0.4 on 2022-04-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='link_instagram',
        ),
    ]
