# Generated by Django 4.0.4 on 2022-04-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='first_photo',
            new_name='first_phot',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='second_photo',
            new_name='second_phot',
        ),
    ]
