# Generated by Django 4.0.4 on 2022-04-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_first_photo_items_first_phot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='first_phot',
            new_name='first_photo',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='second_phot',
            new_name='second_photo',
        ),
    ]
